name: Docker Image Pull Request

on:
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name:  "add-path"
        shell: pwsh
        run: Add-Content $env:GITHUB_PATH "C:\Program Files\Git\bin"
        if: runner.os == 'Windows'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        id: set-vars
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_ORGNAME }}" ]; then
              UNAME=${{ secrets.DOCKER_HUB_USERNAME }}
          else
              UNAME=${{ secrets.DOCKER_HUB_ORGNAME }}
          fi
          if [ -z "${{ secrets.DOCKER_HUB_REPO }}" ]; then
              REPO=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}')
          else
              REPO=${{ secrets.DOCKER_HUB_REPO }}
          fi
          TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's/^main$/latest/g')
          TAG2=$(echo ${{ matrix.platform }} | cut -d/ -f2)
          echo "::set-output name=image::${UNAME}/${REPO}:${TAG}"
          echo "::set-output name=image-tag2::${UNAME}/${REPO}:${TAG}-${TAG2}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build without push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          tags: ${{ steps.set-vars.outputs.image-tag2 }}
