name: Docker Build CI

on:
  push:
    branches: '*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Obtain repository and tag names
        shell: bash
        run: |
             if [ -z "${{ secrets.DOCKER_HUB_REPO }}" ]; then
                 echo "uname=${{ secrets.DOCKER_HUB_USERNAME }}" >> $GITHUB_OUTPUT
             else
                 echo "uname=${{ secrets.DOCKER_HUB_REPO }}" >> $GITHUB_OUTPUT
             fi
             echo "repo=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}')"  >> $GITHUB_OUTPUT
             echo "tag=$(echo ${GITHUB_REF#refs/heads/} | sed 's/^main$/latest/g')" >> $GITHUB_OUTPUT
        id: extract_tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ams562/desktop:${{ steps.extract_tag.outputs.tag }}
          cache-from: type=registry,ref=${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:buildcache
          cache-to: type=registry,ref=${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:buildcache,mode=max

